#
###################################
# Site wide configuration
####################################
#
title: Natalie Cobo
email:
description: Historian of the early modern world, with a focus on the Philippines and Iberian political and legal thought. Oxford DPhil. Co-founder of Neogranadina.
url: https://nataliecobo.com # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
keywords: ["early modern history", "Spanish colonial history", "Latin translation", "digital humanities", "Iberian world", "Philippines", "Santafé de Bogotá", "Juan de Solórzano Pereira", "Neogranadina", "historical research"]

# Social media and SEO
author:
  name: Natalie Cobo

logo: /img/neogranadina.png

social:
  name: Natalie Cobo
  links: []

# Jekyll SEO Tag configuration
tagline: Historian of the early modern Iberian world and translator of early modern Latin texts

lang: en_US

#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Los_Angeles
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

include:
  - _pages

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Natalie Cobo
  avatar: neogranadina.png
  position: "Affiliate Researcher, <br>MPI for Legal History and Legal Theory;<br>Budick Fellow, UC Santa Barbara"
  bio: "Historian of the early modern Iberian world. Translator of early modern Latin texts."
  email:
